### ISSUE TITLE
Actividad 5 Diseno de estructura de libreria DLL

### ISSUE THREAD

**Issue by ArcangelGC** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-4as_coders#1]
[PRACTICA 4 - TRABAJO EN EQUIPO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-4as_coders/files/14669546/PRACTICA.4.-.TRABAJO.EN.EQUIPO.pdf)

**Comment by Kim-Mendoza3** [comment]
Calificacion 20, cuenta con todos los criterios establecidos en la rubrica.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
